### ISSUE TITLE
manifest.json.php error 500 when giving wordpress its own directory

### ISSUE THREAD

**Issue by FreshFlesh** [one-signal/OneSignal-WordPress-Plugin#1]
manifest.json.php assumes wp-load.php file is located 4 level up, which might be a false assumption if WordPress was given its own directory.

Giving WordPress its own directory is pretty common when you are managing your WP projects with SVN externals, GIT or composer.

I think manifest.json.php should be rewritten to use a plugin endpoint which is a better approach and would have WordPress already loaded.

**Comment by jasonpang** [comment]
Sorry, should have responded to this sooner. In the last few versions of our WordPress plugin, we no longer load `wp-load.php`. Sorry about the trouble there.
