### ISSUE TITLE
Feature request: Add ability to segment users through wordpress filtering hook

### ISSUE THREAD

**Issue by henkler** [one-signal/OneSignal-WordPress-Plugin#11]
It would be nice to be able to allow the default 'All' segment to be changed.  That way, every notification doesn't always have to go to every subscriber.

I've created a pull request for this that uses the existing WordPress filtering mechanism to allow this to be dynamically changed in theme/plugin code.  Very easy to implement subscriber filtering this way.

**Comment by jasonpang** [comment]
Hey Henkler,

We decided instead to add a single filter allowing modification of the entire object we post to our create notification API. I've explained it more and added an example in [this reply to your other pull request](https://github.com/one-signal/OneSignal-WordPress-Plugin/pull/12#issuecomment-195170947). Thanks for all the contributions you've made!

**Comment by henkler** [comment]
Great!  This should be flexible enough to work!
