### ISSUE TITLE
Feature Request: Ability to apply custom Tags to Users

### ISSUE THREAD

**Issue by henkler** [one-signal/OneSignal-WordPress-Plugin#13]
It would be beneficial for those with complex segmenting and notification rules to be able to apply tags to users through the WordPress plugin.

For example, we want to tag all WordPress users with the "wordpress" tag.

Or, in a more complicated scenario, we want to tag a user with a paid membership with a "paid-user" tag.

I'll work on some code for this and issue a PR when I'm done.

**Comment by jasonpang** [comment]
Hey Henkler,

We decided instead to add a single filter allowing modification of the entire object we post to our create notification API. I've explained it more and added an example in [this reply to your other pull request](https://github.com/one-signal/OneSignal-WordPress-Plugin/pull/12#issuecomment-195170947). Thanks for all the contributions you've made!

**Comment by henkler** [comment]
Unfortunately, the single filter in onesignal-admin.php won't work for applying custom tags to users. There would have to be another filter in onesignal-public.php.  This filter would have to execute in Javascript on OneSignal.init().

I will put together another filter for onesignal-public that behaves in a similar fashion to the filter you added in onesignal-admin.php, and strip out the admin panel code.

**Comment by jasonpang** [comment]
Hey Henkler,

You're right -- the `onesignal-admin.php` filter would never have worked to apply custom tags to users. The filter for `onesignal-public.php` sounds good but does there have to be extra stuff in the admin page? If possible, we'd like to keep the admin page from having more options. Users who have to use a filter will already be needing to add code. I could be misunderstanding what the admin option is though!

**Comment by henkler** [comment]
I think it would be fine without the admin page stuff.  I'm actually not using it, I just put it in to be helpful for less technical users.
