### ISSUE TITLE
v 1.6.0 turns on error_reporting site-wide

### ISSUE THREAD

**Issue by giles-v** [one-signal/OneSignal-WordPress-Plugin#2]
Top two lines of the public file:

https://github.com/one-signal/OneSignal-WordPress-Plugin/blob/be7d9e5ac7a683e25c45b47e2ce4dbecac783172/onesignal-public.php#L2-L3

This is a security risk, quite apart from the design problems it causes throwing low-level notice errors across the site.

**Comment by jasonpang** [comment]
Sorry about that giles-v. It caused quite a few problems and it's been fixed in v1.7.0.
