### ISSUE TITLE
Add filter to onesignal-admin.php

### ISSUE THREAD

**Issue by mihdan** [one-signal/OneSignal-WordPress-Plugin#22]
Don't work with plugin Edit Flow (custom statuses). 
Please add a filter in the condition `in_array($post->post_status, array("future", "draft", "auto-draft", "pending"));`

Thx

**Comment by jasonpang** [comment]
Hi,

Could you please provide a detailed example of what isn't working possibly with steps to reproduce? What kind of filter do you think would be necessary to fix whatever is breaking?

**Comment by mihdan** [comment]
We use the Edit Flow plugin, which set the final status of the article `done`.
Your plugin sets tough conditions for checkboxes selection:

`in_array ($ post-> post_status, array ( "future", "draft", "auto-draft", "pending"));`

Since we can not filter array with statuses, we can not add our status `done`. Therefore checked by default is not put into the active state in the article metaboxes,  and push notifications  do not go away.

We need:

`in_array($post->post_status, apply_filters( 'filter_was_where', array("future", "draft", "auto-draft", "pending") ) );`

**Comment by jasonpang** [comment]
Fixed by: https://github.com/one-signal/OneSignal-WordPress-Plugin/commit/b5b6a32fd359626ad27f0ea5999f5d1f250cb212.

**Comment by jasonpang** [comment]
e.g.

```php
add_filter('onesignal_meta_box_send_notification_checkbox_state', 'onesignal_meta_box_send_notification_checkbox_state_filter', 10, 4);
function onesignal_meta_box_send_notification_checkbox_state_filter($post, $onesignal_wp_settings) {
    return false;
}
```

**Comment by mihdan** [comment]
Thx
