### ISSUE TITLE
Feature request: Add additional data 

### ISSUE THREAD

**Issue by Ralphilius** [one-signal/OneSignal-WordPress-Plugin#23]
Hello,

I want to set up scheduled push notification from WordPress which is a CMS for my application. However, the app needs some additional data like post_id and some custom field to respond to `notificationOpened` call. Please allow post meta and custom fields to send along with the push.

Thanks,

**Comment by jasonpang** [comment]
Hey Ralphilius,

I believe this can be done by using PHP to add a WordPress filter hook. Our plugin has a filter hook for sending out notifications that you can use to add additional data:

Here's an example:

```php
add_filter('onesignal_send_notification', 'onesignal_send_notification_filter', 10, 4);
function onesignal_send_notification_filter($fields, $new_status, $old_status, $post) {
  $fields['headings'] = array("en" => "my modified title!");
  $fields['isAndroid'] = true;
  return $fields;
}   
```

The full documentation for what parameters are usable is here: https://documentation.onesignal.com/docs/notifications-create-notification

**Comment by Ralphilius** [comment]
Hi @jasonpang 

Where should I put these codes? I'm not familiar with writing WordPress plugin/codes.

**Comment by jasonpang** [comment]
Hey Ralphilius,

Can you try putting this code in one of the PHP files of your WordPress theme? I'd try to place this in a PHP file that will get called all the time, like maybe a header or footer theme file. The exact code above won't add additional data; you can check our documentation page on how to add the right parameter to the `$fields` array for that.
