### ISSUE TITLE
Add ability to set persistNotification: false via the WordPress plugin

### ISSUE THREAD

**Issue by andrewkhunn** [one-signal/OneSignal-WordPress-Plugin#6]
Could you please add a toggle in the WordPress admin setting to enable automatic dismissal of messages after ~20 seconds in Chrome? There doesn't appear to be an easy method to inject this flag when using the plugin.

**Comment by jasonpang** [comment]
Hey Andrew,

Another developer contributed that feature to our plugin, so that will be available!
