### ISSUE TITLE
Feature request: Option to add featured image icon support to notifications

### ISSUE THREAD

**Issue by henkler** [one-signal/OneSignal-WordPress-Plugin#8]
When a notification is sent, it would be desirable to have an option link the WordPress featured image icon (80x80px) to the notification.

Both Firefox and Chrome Desktop support this, and it makes the notifications look much more appealing.

I've submitted a pull request with the code modifications to support this.

**Comment by jasonpang** [comment]
Hi Henkler,

We support this now (the commit at least after `f0b8ee9564a0e45aad5b9303cb2160658ebf9df1` should have the changes, it should have been added a few commits before this one).
